# Generated by Django 4.2 on 2024-08-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО клиента')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Краткое наименование рассылки')),
                ('first_sending_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время первой рассылки')),
                ('periodicity', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], default='daily', max_length=20, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('new', 'создана'), ('finished', 'завершена'), ('started', 'запущена')], default='new', max_length=10, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(to='main.client', verbose_name='Клиенты для рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('body', models.TextField(verbose_name='Тело сообщения')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней рассылки')),
                ('status', models.CharField(blank=True, choices=[('success', 'успешно'), ('unsuccess', 'не успешно')], max_length=15, null=True, verbose_name='Статус попытки')),
                ('server_answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
