# Generated by Django 4.2 on 2024-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_owner_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='first_sending_time',
            new_name='first_sending',
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='last_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней отправки рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='next_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующей отправки рассылки'),
        ),
    ]
