# Generated by Django 4.2 on 2024-08-05 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_first_sending_time_mailing_first_sending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус попытки'),
        ),
    ]
