# Generated by Django 4.2 on 2024-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification_remove_mailing_message_delete_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='attempt_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата и время последней рассылки'),
        ),
    ]
