# Generated by Django 4.2 on 2024-08-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_attempt_attempt_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='attempt_date',
            new_name='attempt_time',
        ),
    ]
