# Generated by Django 4.2 on 2024-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_attempt_date_attempt_attempt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='client',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Адресат'),
        ),
    ]
