# Generated by Django 4.2 on 2024-08-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_attempt_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_disable_mailings', 'can_disable_mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
