# Generated by Django 4.2 on 2024-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mailing_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='block_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата автоматической деактивации рассылки'),
        ),
    ]
